### ISSUE TITLE
npm install puppeteer issue & Folder dist/index.js > dist/src/index.js

### ISSUE THREAD

**Issue by Renaenys** [Ionaru/MarketBot#9]
npm install puppeteer issue & Folder dist/index.js > dist/src/index.js
=)
o7
sql lite not insdide the npm install too =)

**Comment by Ionaru** [comment]
I don't know what you mean by this.

Both `puppeteer` and `sqlite3` are listed in https://github.com/Ionaru/MarketBot/blob/master/package.json
